### ISSUE TITLE
1.19.4 Support

### ISSUE THREAD

**Issue by Simmo06** [InventivetalentDev/PacketListenerAPI#122]
It looks like the plugin is throwing errors in my 1.19.4 MC server. I need this plugin, as it's a dependency. Will you be making this update?

at PacketListenerAPI_v3.9.10-SNAPSHOT.jar//org.inventivetalent.packetlistener.PacketListenerPlugin.onLoad(PacketListenerPlugin.java:16)
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423)
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Simmo06** [comment]
`[PacketListenerApi] [STDERR] [ReflectionHelper] Failed to find version enum for 'org.bukkit.craftbukkit.v1_19_R3'/'v1_19_R3`

**Comment by PartOfCheese** [comment]
Yeah I need 1.19.4 update too

**Comment by srnyx** [comment]
https://github.com/InventivetalentDev/PacketListenerAPI/pull/119
