### ISSUE TITLE
Error with spigot 1.8.8

### ISSUE THREAD

**Issue by LoSunny** [InventivetalentDev/PacketListenerAPI#13]
I don't know why I get this error when I start my server
```
[12:05:46 INFO]: [PacketListenerAPI] Using INChannel
[12:05:46 WARN]: java.lang.NoSuchFieldException: list
[12:05:46 WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[12:05:46 WARN]: 	at org.inventivetalent.packetlistener.channel.ChannelAbstract.addServerChannel(ChannelAbstract.java:69)
[12:05:46 WARN]: 	at org.inventivetalent.packetlistener.ChannelInjector.addServerChannel(ChannelInjector.java:55)
[12:05:46 WARN]: 	at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32)
[12:05:46 WARN]: 	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46)
[12:05:46 WARN]: 	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:65)
[12:05:46 WARN]: 	at org.inventivetalent.packetlistener.PacketListenerPlugin.onLoad(PacketListenerPlugin.java:17)
[12:05:46 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
[12:05:46 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[12:05:46 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[12:05:46 WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
PacketListenerApi version 3.6.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
[12:07:48 INFO]: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[12:07:48 INFO]: Checking version, please wait...
[12:07:50 INFO]: You are 774 version(s) behind

## What plugins are you using? *Type /plugins*  
Plugins (36): LuckPerms, WorldEdit, MBanProxyVPN, PlaceholderAPI, PacketListenerApi, AntiAuraMessages, PlugMan, MineSecure, Spartan, SkinsRestorer, MineSec, SpartanAlerts, Vault, MyCommand, ProtocolSupport, Statz, NickNamer, SimpleRename, ViaVersion, ProtocolLib, LibsDisguises, NoCheatPlus, AAC, UHCReloaded, ChatItem, React, TrollCommandsPlusPlus, PacketWrapper, AntiAura, SuperVanish, iControlU, Orebfuscator3, DakataAntiCheat, ClientStats, Statscraft, CMI

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no

**Comment by Dymeth** [comment]
Same.

**Plugin version**:
PacketListenerApi version 3.7.3-SNAPSHOT

**Spigot version:**
This server is running Paper version git-Paper-642 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Previous version: git-Paper-638 (MC: 1.13.2)
You are 3 version(s) behind

**Plugins:**
AnimatedFrames*, ArmorStandTools, BKCommonLib, Citizens, DiceFurniture, DiscordSRV, dynmap*, elyby-skinsystem*, Essentials, FastAsyncVoxelSniper, FastAsyncWorldEdit, FurnitureLib, goBrush, goPaint, HeadDatabase*, HolographicDisplays, LibsDisguises, LightAPI*, LightCleaner, LuckPerms, MapManager*, MultiWorld*, PacketListenerApi*, PlugMan, ProtectionLib*, ProtocolLib*, ProtocolSupport, ProtocolSupportPotions, SelectionVisualizer, spark, Spartan, Vault, ViaVersion*, VoidGenerator, WorldBorder, WorldEdit

**Java version:**
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**Logs:**
[PacketListenerApi] Loading PacketListenerApi v3.7.3-SNAPSHOT
[ReflectionHelper] I am loaded from package org.inventivetalent.packetlistener.reflection.minecraft
[ReflectionHelper] Version is v1_13_R2 (11302)
[PacketListenerAPI] Using INChannel
java.lang.NoSuchFieldException: list
	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
	at org.inventivetalent.packetlistener.channel.ChannelAbstract.addServerChannel(ChannelAbstract.java:69)
	at org.inventivetalent.packetlistener.ChannelInjector.addServerChannel(ChannelInjector.java:55)
	at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32)
	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46)
	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:65)
	at org.inventivetalent.packetlistener.PacketListenerPlugin.onLoad(PacketListenerPlugin.java:18)
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:336)
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
	at java.base/java.lang.Thread.run(Thread.java:834)
[PacketListenerAPI] Injected custom channel handlers.

**Comment by InventivetalentDev** [comment]
You should be able to ignore that error without it causing any issues.
