### ISSUE TITLE
Can we add a disable for the update check. It's annoying. Thanks

### ISSUE THREAD

**Issue by madtomic** [InventivetalentDev/PacketListenerAPI#17]
[13:44:19 WARN]: [PacketListenerApi] Failed to get resource info from spiget.org
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
        at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[patched_1.12.2.jar:git-Paper-1332]
        at org.inventivetalent.update.spiget.SpigetUpdateAbstract$1.run(SpigetUpdateAbstract.java:92) [PacketListenerAPI_v3.6.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12.2.jar:git-Paper-1332]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1332]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1332]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[patched_1.12.2.jar:git-Paper-1332]
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[patched_1.12.2.jar:git-Paper-1332]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[patched_1.12.2.jar:git-Paper-1332]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[patched_1.12.2.jar:git-Paper-1332]
        at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[patched_1.12.2.jar:git-Paper-1332]
        ... 7 more
[13:44:19 INFO]: [CS-CoreLib - Protection] Loaded Protection Module "WorldGuard"
[13:44:19 WARN]: [ShopChest] Plugin ShopChest v1.12.3 generated an exception while executing task 103
java.lang.ArrayIndexOutOfBoundsException: 1
        at de.epiceric.shopchest.utils.UpdateChecker.check(UpdateChecker.java:44) ~[?:?]
        at de.epiceric.shopchest.ShopChest$4.run(ShopChest.java:321) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1332]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1332]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1332]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]

**Comment by InventivetalentDev** [comment]
Looks like this is more of an issue with your server setup in general, telling from the other updater errors in your log.
