### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by LuisDasNilpferd** [InventivetalentDev/PacketListenerAPI#37]
[00:17:15] [Server thread/INFO]: API class 'org.inventivetalent.packetlistener.PacketListenerAPI' is not yet initialized. Creating new instance.
[00:17:15] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.Channel
[00:17:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[00:17:15] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[00:17:15] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[00:17:15] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[00:17:15] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.ChannelInjector.inject(ChannelInjector.java:21)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:31)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:117)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.nicknamer.NickNamerPlugin.onEnable(NickNamerPlugin.java:170)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[00:17:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[00:17:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[00:17:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[00:17:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[00:17:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[00:17:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:17:15] [Server thread/WARN]: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='org.inventivetalent.packetlistener.channel.INCChannel', types=[]}]
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:40)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:8)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:60)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:27)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.ChannelInjector.newChannelInstance(ChannelInjector.java:43)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.ChannelInjector.inject(ChannelInjector.java:30)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:31)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:117)
[00:17:15] [Server thread/WARN]: 	at org.inventivetalent.nicknamer.NickNamerPlugin.onEnable(NickNamerPlugin.java:170)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[00:17:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[00:17:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[00:17:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[00:17:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[00:17:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[00:17:15] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[00:17:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:17:15] [Server thread/ERROR]: Failed to inject channel handlers
[00:17:15] [Server thread/INFO]: Adding channels for online players...

**Comment by InventivetalentDev** [comment]
Use the template.
