### ISSUE TITLE
NoSuchElementException: packet_listener_player

### ISSUE THREAD

**Issue by mixxit** [InventivetalentDev/PacketListenerAPI#41]
[PacketListenerApi] Loading PacketListenerApi v3.7.3-SNAPSHOT

This server is running CraftBukkit version git-Spigot-065a373-8d4bc54 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

```[19:10:43] [pool-6-thread-1/WARN]: Exception in thread "pool-6-thread-1"
[19:10:43] [pool-6-thread-1/WARN]: java.lang.RuntimeException: java.util.NoSuchElementException: packet_listener_player
[19:10:43] [pool-6-thread-1/WARN]:      at org.inventivetalent.packetlistener.channel.INCChannel$2.run(INCChannel.java:54)
[19:10:43] [pool-6-thread-1/WARN]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:10:43] [pool-6-thread-1/WARN]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:10:43] [pool-6-thread-1/WARN]:      at java.lang.Thread.run(Thread.java:748)
[19:10:43] [pool-6-thread-1/WARN]: Caused by: java.util.NoSuchElementException: packet_listener_player
[19:10:43] [pool-6-thread-1/WARN]:      at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119)
[19:10:43] [pool-6-thread-1/WARN]:      at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:451)
[19:10:43] [pool-6-thread-1/WARN]:      at com.comphenix.protocol.injector.netty.PipelineProxy.remove(PipelineProxy.java:318)
[19:10:43] [pool-6-thread-1/WARN]:      at org.inventivetalent.packetlistener.channel.INCChannel$2.run(INCChannel.java:51)
[19:10:43] [pool-6-thread-1/WARN]:      ... 3 more```

**Comment by mixxit** [comment]
```
[16:47:46] [pool-6-thread-1/WARN]: Exception in thread "pool-6-thread-1"
[16:47:46] [pool-6-thread-1/WARN]: java.lang.RuntimeException: java.util.NoSuchElementException: packet_listener_player
[16:47:46] [pool-6-thread-1/WARN]:      at org.inventivetalent.packetlistener.channel.INCChannel$2.run(INCChannel.java:54)
[16:47:46] [pool-6-thread-1/WARN]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:47:46] [pool-6-thread-1/WARN]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:47:46] [pool-6-thread-1/WARN]:      at java.lang.Thread.run(Thread.java:748)
[16:47:46] [pool-6-thread-1/WARN]: Caused by: java.util.NoSuchElementException: packet_listener_player
[16:47:46] [pool-6-thread-1/WARN]:      at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119)
[16:47:46] [pool-6-thread-1/WARN]:      at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:451)
[16:47:46] [pool-6-thread-1/WARN]:      at com.comphenix.protocol.injector.netty.PipelineProxy.remove(PipelineProxy.java:318)
[16:47:46] [pool-6-thread-1/WARN]:      at org.inventivetalent.packetlistener.channel.INCChannel$2.run(INCChannel.java:51)
[16:47:46] [pool-6-thread-1/WARN]:      ... 3 more
```
