### ISSUE TITLE
Errors with Java 14

### ISSUE THREAD

**Issue by Patbox** [InventivetalentDev/PacketListenerAPI#61]
## What steps will reproduce the problem?  
1. Install this plugin (with GlowAPI)
2. Start server with Java 14

## What were you expecting to happen? What happened instead? 
Just to not get errors

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
![image](https://user-images.githubusercontent.com/39821509/78529466-f598cc00-77e1-11ea-8371-d79cc93f8595.png)

## What Spigot version are you using? *Type /version*  
![image](https://user-images.githubusercontent.com/39821509/78529442-ec0f6400-77e1-11ea-9192-86052af1c04a.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
```[08:24:23 INFO]: [PacketListenerAPI] Using INChannel
[08:24:23 WARN]: java.lang.NullPointerException
[08:24:23 WARN]: 	at org.inventivetalent.packetlistener.channel.ChannelAbstract.addServerChannel(ChannelAbstract.java:66)
[08:24:23 WARN]: 	at org.inventivetalent.packetlistener.ChannelInjector.addServerChannel(ChannelInjector.java:55)
[08:24:23 WARN]: 	at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32)
[08:24:23 WARN]: 	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46)
[08:24:23 WARN]: 	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:65)
[08:24:23 WARN]: 	at org.inventivetalent.packetlistener.PacketListenerPlugin.onLoad(PacketListenerPlugin.java:18)
[08:24:23 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:363)
[08:24:23 WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235)
[08:24:23 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[08:24:23 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[08:24:23 INFO]: [PacketListenerAPI] Injected custom channel handlers.
...
[08:26:19 ERROR]: Could not pass event PlayerJoinEvent to PacketListenerApi v3.7.5-SNAPSHOT
java.lang.NullPointerException: null
	at org.inventivetalent.packetlistener.channel.INCChannel.getChannel(INCChannel.java:65) ~[?:?]
	at org.inventivetalent.packetlistener.channel.INCChannel.addChannel(INCChannel.java:26) ~[?:?]
	at org.inventivetalent.packetlistener.ChannelInjector.addChannel(ChannelInjector.java:47) ~[?:?]
	at org.inventivetalent.packetlistener.PacketListenerAPI.onJoin(PacketListenerAPI.java:89) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor129.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:268) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1267) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Tuinity-"b2e87f8"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[08:26:19 INFO]: [ReflectionHelper] I am loaded from package org.inventivetalent.glow.reflection.minecraft
[08:26:19 INFO]: [ReflectionHelper] Version is v1_15_R1 (11501)

```
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Nope
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
It worked with Java 11.

**Comment by TheGreyRaven** [comment]
Can also confirm this issue, some more errors:
```
[17:39:54 ERROR]: Could not pass event PlayerQuitEvent to PacketListenerApi v3.7.5-SNAPSHOT
java.lang.NullPointerException: null
        at org.inventivetalent.packetlistener.channel.INCChannel.getChannel(INCChannel.java:65) ~[?:?]
        at org.inventivetalent.packetlistener.channel.INCChannel.removeChannel(INCChannel.java:45) ~[?:?]
        at org.inventivetalent.packetlistener.ChannelInjector.removeChannel(ChannelInjector.java:51) ~[?:?]
        at org.inventivetalent.packetlistener.PacketListenerAPI.onQuit(PacketListenerAPI.java:94) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.EventExecutor$$Lambda$2592/0000000000000000.execute(Unknown Source) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.PlayerList.disconnect(PlayerList.java:411) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[?:git-Paper-183]
        at net.minecraft.server.v1_15_R1.NetworkManager.handleDisconnection(NetworkManager.java:356) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:163) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1133) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:941) ~[patched_1.15.2.jar:git-Paper-183]
        at java.lang.Thread.run(Unknown Source) [?:?]
```
```
[17:35:08] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to PacketListenerApi v3.7.5-SNAPSHOT
java.lang.NullPointerException: null
	at org.inventivetalent.packetlistener.channel.INCChannel.getChannel(INCChannel.java:65) ~[?:?]
	at org.inventivetalent.packetlistener.channel.INCChannel.addChannel(INCChannel.java:26) ~[?:?]
	at org.inventivetalent.packetlistener.ChannelInjector.addChannel(ChannelInjector.java:47) ~[?:?]
	at org.inventivetalent.packetlistener.PacketListenerAPI.onJoin(PacketListenerAPI.java:89) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor54.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.EventExecutor$$Lambda$2592/0000000000000000.execute(Unknown Source) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:193) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1133) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:941) ~[patched_1.15.2.jar:git-Paper-183]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

GlowAPI also throws error:
```
[17:35:08] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to GlowAPI v1.4.11-SNAPSHOT
java.lang.NullPointerException: null
	at org.inventivetalent.glow.reflection.util.AccessUtil.setAccessible(AccessUtil.java:26) ~[?:?]
	at org.inventivetalent.glow.reflection.resolver.FieldResolver.resolveObject(FieldResolver.java:82) ~[?:?]
	at org.inventivetalent.glow.reflection.resolver.FieldResolver.resolveObject(FieldResolver.java:11) ~[?:?]
	at org.inventivetalent.glow.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:50) ~[?:?]
	at org.inventivetalent.glow.reflection.resolver.FieldResolver.resolve(FieldResolver.java:57) ~[?:?]
	at org.inventivetalent.glow.GlowAPI.sendTeamPacket(GlowAPI.java:359) ~[?:?]
	at org.inventivetalent.glow.GlowAPI.initTeam(GlowAPI.java:333) ~[?:?]
	at org.inventivetalent.glow.GlowAPI.initTeam(GlowAPI.java:343) ~[?:?]
	at org.inventivetalent.glow.GlowAPI.onJoin(GlowAPI.java:536) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor56.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.EventExecutor$$Lambda$2592/0000000000000000.execute(Unknown Source) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:193) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1133) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:941) ~[patched_1.15.2.jar:git-Paper-183]
	at java.lang.Thread.run(Unknown Source) [?:?]
```
```
[18:08:57] [Server thread/WARN]: java.lang.NullPointerException
[18:08:57] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.channel.ChannelAbstract.addServerChannel(ChannelAbstract.java:66)
[18:08:57] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.ChannelInjector.addServerChannel(ChannelInjector.java:55)
[18:08:57] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32)
[18:08:57] [Server thread/WARN]: 	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46)
[18:08:57] [Server thread/WARN]: 	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:65)
[18:08:57] [Server thread/WARN]: 	at org.inventivetalent.packetlistener.PacketListenerPlugin.onLoad(PacketListenerPlugin.java:18)
[18:08:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:363)
[18:08:57] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234)
[18:08:57] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:891)
[18:08:57] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by InventivetalentDev** [comment]
So you're both certain this is an issue with Java 14? Did it work fine for your current server setup (version, plugins, etc.) with an earlier Java version?

**Comment by TheGreyRaven** [comment]
> So you're both certain this is an issue with Java 14? Did it work fine for your current server setup (version, plugins, etc.) with an earlier Java version?

Yes works fine with Latest Paper and Java 11 with only PacketListenerAPI and GlowAPI.
And the errors above occurs with just those 2 plugins and latest Paper.

**Comment by Patbox** [comment]
Everything worked with Java 11

**Comment by InventivetalentDev** [comment]
Seems to be caused by the Reflection changes in JDK12+ preventing the necessary changes to protected fields http://mail.openjdk.java.net/pipermail/core-libs-dev/2018-November/056486.html

**Comment by InventivetalentDev** [comment]
~~For now, the only "solution" I can offer is to just use Java 11 until I can figure out a better way to get around this issue.~~

**Comment by TheGreyRaven** [comment]
@InventivetalentDev Hello again, I just wanted to let you know that your referenced commit did not help with the issue.
I'm not sure if this might be of any use but the Java I use it this https://adoptopenjdk.net/releases.html?variant=openjdk14&jvmVariant=openj9
OpenJDK14 with OpenJ9!

**Comment by InventivetalentDev** [comment]
Hmm I did try it with Java 14 and it worked fine though 🤔

**Comment by TheGreyRaven** [comment]
> Hmm I did try it with Java 14 and it worked fine though

Hm interesting, do you the same Java as in my link?
I can supply you with full system specs and launch arguments if that might be of help.
Ill double check everything in an hour or so and come back with the result, I just did a quick test and I got the same error as before, but I will double check!

**Comment by TheGreyRaven** [comment]
@InventivetalentDev So the issue still persist for me, heres the error:
```
[03:02:42 ERROR]: Could not pass event PlayerJoinEvent to PacketListenerApi v3.7.6-SNAPSHOT
java.lang.NullPointerException: null
        at org.inventivetalent.packetlistener.channel.INCChannel.getChannel(INCChannel.java:65) ~[?:?]
        at org.inventivetalent.packetlistener.channel.INCChannel.addChannel(INCChannel.java:26) ~[?:?]
        at org.inventivetalent.packetlistener.ChannelInjector.addChannel(ChannelInjector.java:47) ~[?:?]
        at org.inventivetalent.packetlistener.PacketListenerAPI.onJoin(PacketListenerAPI.java:89) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.EventExecutor$$Lambda$2505/0000000000000000.execute(Unknown Source) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:193) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1133) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:941) ~[patched_1.15.2.jar:git-Paper-183]
        at java.lang.Thread.run(Unknown Source) [?:?]
```
I also get error for when disconnecting.

Java that I use:
https://adoptopenjdk.net/releases.html?variant=openjdk14&jvmVariant=openj9

Paper version:
#183

Plugins:
Just PacketListenerAPI

Server:
Ubuntu 18.04

Let me know if there is anything else you need!

**Comment by InventivetalentDev** [comment]
Looks like the particular JDK you're using doesn't support the workaround I implemented.

**Comment by TheGreyRaven** [comment]
> Looks like the particular JDK you're using doesn't support the workaround I implemented.

Thats a shame, guess Ill have to move over to Oracle for now, maybe it is a bit to early to ask but do you think OpenJDK will be supported in the future?
My server greatly benefits from OpenJDK and OpenJ9 as it boots up the server much faster than regular Java & Hotspot.
Anyway thank you for looking into it!
