### ISSUE TITLE
[BUG REPORT] Console spam

### ISSUE THREAD

**Issue by melody-rs** [InventivetalentDev/PacketListenerAPI#73]
```[22:51:29 WARN]: [PacketListenerAPI] An exception occured while trying to execute 'onSend' in plugin NickNamer: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='action', types=[]}] in class class net.minecraft.server.v1_16_R3.PacketPlayOutPlayerInfo
[22:51:29 WARN]: java.lang.RuntimeException: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='action', types=[]}] in class class net.minecraft.server.v1_16_R3.PacketPlayOutPlayerInfo
[22:51:29 WARN]: 	at org.inventivetalent.packetlistener.handler.PacketAbstract.getPacketValue(PacketAbstract.java:100)
[22:51:29 WARN]: 	at org.inventivetalent.nicknamer.api.PacketListener.onSend(PacketListener.java:90)
[22:51:29 WARN]: 	at org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:81)
[22:51:29 WARN]: 	at org.inventivetalent.packetlistener.PacketListenerAPI.onPacketSend(PacketListenerAPI.java:118)
[22:51:29 WARN]: 	at org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketSend(ChannelAbstract.java:85)
[22:51:29 WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:140)
[22:51:29 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[22:51:29 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[22:51:29 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[22:51:29 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[22:51:29 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[22:51:29 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[22:51:29 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[22:51:29 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[22:51:29 WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:300)
[22:51:29 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[22:51:29 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[22:51:29 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[22:51:29 WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[22:51:29 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[22:51:29 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[22:51:29 WARN]: Caused by: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='action', types=[]}] in class class net.minecraft.server.v1_16_R3.PacketPlayOutPlayerInfo
[22:51:29 WARN]: 	at org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:218)
[22:51:29 WARN]: 	at org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:11)
[22:51:29 WARN]: 	at org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:60)
[22:51:29 WARN]: 	at org.inventivetalent.packetlistener.reflection.resolver.FieldResolver.resolve(FieldResolver.java:57)
[22:51:29 WARN]: 	at org.inventivetalent.packetlistener.handler.PacketAbstract.getPacketValue(PacketAbstract.java:98)
[22:51:29 WARN]: 	... 20 more
```

Is flooding console after updating to 1.16.4.
Please make a sperate bug report issue template rather than just a feature request.

**Comment by InventivetalentDev** [comment]
https://github.com/InventivetalentDev/NickNamer
