### ISSUE TITLE
Exception spam when joined server

### ISSUE THREAD

**Issue by vytskalt** [InventivetalentDev/PacketListenerAPI#83]
## What steps will reproduce the problem?  
Join the server

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.8.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
This server is running CraftBukkit version git-SportPaper-v1.0-16-g934b4b2 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  
Only PacketListenerAPI

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
When you join the server, this gets constantly spammed:
```
[21:59:03] [Netty Epoll Server IO #1/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer
	at io.netty.channel.epoll.Native.read(Native Method) ~[server.jar:git-SportPaper-v1.0-16-g934b4b2]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678) [server.jar:git-SportPaper-v1.0-16-g934b4b2]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714) [server.jar:git-SportPaper-v1.0-16-g934b4b2]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755) [server.jar:git-SportPaper-v1.0-16-g934b4b2]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [server.jar:git-SportPaper-v1.0-16-g934b4b2]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [server.jar:git-SportPaper-v1.0-16-g934b4b2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:git-SportPaper-v1.0-16-g934b4b2]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
```

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I'm running the server on a Ubuntu machine with Java 11 installed. I'm also using a fork of Spigot 1.8.8 (https://github.com/Electroid/SportPaper/).

**Comment by vytskalt** [comment]
Nvm found the issue
