### ISSUE TITLE
InaccessibleObjectException on startup with Java 16

### ISSUE THREAD

**Issue by GriffinCodes** [InventivetalentDev/PacketListenerAPI#89]
## What steps will reproduce the problem?  
1. Install v3.8.0 on a server using java 16
2. Start server
3. Observe following error: 
```
2021-05-13 10:55:50 | [PacketListenerApi] Loading PacketListenerApi v3.8.0-SNAPSHOT
2021-05-13 10:55:50 | [ReflectionHelper/MinecraftVersion] I am loaded from package org.inventivetalent.packetlistener.reflection.minecraft
2021-05-13 10:55:50 | [ReflectionHelper/MinecraftVersion] Version is v1_16_R3 (11603)
2021-05-13 10:55:50 | [PacketListenerAPI] Using INChannel
2021-05-13 10:55:50 | [WARN] java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "org.inventivetalent.packetlistener.channel.ChannelAbstract.serverConnection" is null
2021-05-13 10:55:50 | [WARN] at org.inventivetalent.packetlistener.channel.ChannelAbstract.addServerChannel(ChannelAbstract.java:66)
2021-05-13 10:55:50 | [WARN] at org.inventivetalent.packetlistener.ChannelInjector.addServerChannel(ChannelInjector.java:55)
2021-05-13 10:55:50 | [WARN] at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32)
2021-05-13 10:55:50 | [WARN] at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46)
2021-05-13 10:55:50 | [WARN] at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:65)
2021-05-13 10:55:50 | [WARN] at org.inventivetalent.packetlistener.PacketListenerPlugin.onLoad(PacketListenerPlugin.java:18)
2021-05-13 10:55:50 | [WARN] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394)
2021-05-13 10:55:50 | [WARN] at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252)
2021-05-13 10:55:50 | [WARN] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
2021-05-13 10:55:50 | [WARN] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
2021-05-13 10:55:50 | [WARN] at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-13 10:55:50 | [PacketListenerAPI] Injected custom channel handlers.

```

## What Spigot version are you using?
![image](https://user-images.githubusercontent.com/12417961/118143375-444b6900-b3d9-11eb-91f8-c252bc75b176.png)

Custom Paper fork, uses Paper #654

# Additional information
Does not happen on java 15

**Comment by MrMineToons** [comment]
Same here! Using version 3.9.2-SNAPSHOT
