### ISSUE TITLE
Unable to load PacketListenerAPI on Spigot 1.17

### ISSUE THREAD

**Issue by OBattler** [InventivetalentDev/PacketListenerAPI#96]
## What steps will reproduce the problem?  
1. Install Spigot 1.17 and PacketListenerAPI 3.9.2.
2. 
3. 

## What were you expecting to happen? What happened instead?  
I was expecting it to load. Instead, I got an error caused by a reference to net.minecraft.server.Entity.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Version 3.9.2.

## What Spigot version are you using? *Type /version*  
Spigot for 1.17. Can't type /version right now because my server is down.

## What plugins are you using? *Type /plugins*  
PacketListenerAPI, MapManager, AnimatedFrames, PurpleIRC, WirelessRedstone, Multivere-Core, Chairs Reloaded, Stargate, WorldEdit.

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Unfortunately I do not right but I can restart the server and obtain the error if needed.

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
The client is OK, even the server itself did not crash, just PacketListenerAPI refuses to load with that error.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
It worked fine on 1.16.5. I'm not using BungeeCord.

**Comment by Tvhee-Dev** [comment]
Same issue, it simply won't load on 1.17

**Comment by MrMineToons** [comment]
Same

**Comment by Plasman888** [comment]
Same

**Comment by craciu25yt** [comment]
same in 1.8

**Comment by GriffinCodes** [comment]
Here's the actual error since no one else provided it 
```
[16:15:48] [Server thread/INFO]: [PacketListenerApi] Loading PacketListenerApi v3.9.2-SNAPSHOT
[16:15:48] [Server thread/INFO]: [ReflectionHelper/MinecraftVersion] I am loaded from package org.inventivetalent.packetlistener.reflection.minecraft
[16:15:48] [Server thread/INFO]: [ReflectionHelper/MinecraftVersion] Version is v1_17_R1 (11701)
[16:15:48] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_17_R1.CraftServer] null initializing PacketListenerApi v3.9.2-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:15) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveSilent(ClassResolver.java:17) ~[?:?]
	at org.inventivetalent.packetlistener.channel.ChannelAbstract.<clinit>(ChannelAbstract.java:22) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:37) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolveObject(ClassResolver.java:9) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:53) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:29) ~[?:?]
	at org.inventivetalent.packetlistener.ChannelInjector.newChannelInstance(ChannelInjector.java:41) ~[?:?]
	at org.inventivetalent.packetlistener.ChannelInjector.inject(ChannelInjector.java:28) ~[?:?]
	at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32) ~[?:?]
	at org.inventivetalent.packetlistener.PacketListenerPlugin.onLoad(PacketListenerPlugin.java:16) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:400) ~[patched_1.17.jar:git-Paper-"6018ed1"]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:274) ~[patched_1.17.jar:git-Paper-"6018ed1"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"6018ed1"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"6018ed1"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_17_R1.Entity', types=[]}]
	at org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:55) ~[?:?]
	... 18 more
Caused by: java.lang.ClassNotFoundException: Could not resolve class for [ResolverQuery{name='net.minecraft.server.v1_17_R1.Entity', types=[]}]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:42) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.notFoundException(ClassResolver.java:9) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:63) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.ClassResolver.resolve(ClassResolver.java:29) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.resolver.minecraft.NMSClassResolver.resolve(NMSClassResolver.java:18) ~[?:?]
	at org.inventivetalent.packetlistener.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:52) ~[?:?]
	... 18 more
```

**Comment by Dymeth** [comment]
https://github.com/InventivetalentDev/PacketListenerAPI/releases/3.9.3-SNAPSHOT
But has no jar-file in release :(

**Comment by OBattler** [comment]
That's because build is failing with the following error:
```
Error:  Failed to execute goal on project api: Could not resolve dependencies for project org.inventivetalent.packetlistenerapi:api:jar:3.9.3-SNAPSHOT: Failed to collect dependencies at org.inventivetalent.spiget-update:bukkit:jar:1.4.2-SNAPSHOT: Failed to read artifact descriptor for org.inventivetalent.spiget-update:bukkit:jar:1.4.2-SNAPSHOT: Could not transfer artifact org.inventivetalent.spiget-update:parent:pom:parent from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [md_5-repo (http://repo.md-5.net/content/repositories/public/, default, releases+snapshots)] -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :api
Error: Process completed with exit code 1.
```

**Comment by Kush-S-Patel** [comment]
same

**Comment by LoneDev6** [comment]
It works fine on 1.17.1
